NCIHealthStore/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#about'

  get '/about' => 'static_pages#about'
  
  resources :order_items, only: [:index]
  
  resources :purchase_orders do
    resources :order_items, only: [:show, :create, :new, :update, :edit, :destroy]
  end
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

NCIHealthStore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NCIHealthStore/app/models/order_item.rb
class OrderItem < ApplicationRecord
    
    belongs_to :purchase_order, inverse_of: :order_items
    validates_presence_of :purchase_order
    
    validates :item_title,  :item_description, :item_quantity, :item_price, presence: true
    
end

NCIHealthStore/app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
    
    has_many :order_items
    
    validates :client_number, :delivery_address, :delivery_city, :delivery_country, :delivery_fee, presence: true
    
    def calculate_total
        order_items.inject(0){|sum,i| sum += i.item_quantity * i.item_price}+ delivery_fee.to_s.to_d
    end
    
end

NCIHealthStore/app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: true, presence: true, allow_blank: false
    validates :name, :password_digest, presence: true
    
end

NCIHealthStore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  
  def current_user 
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def authenticate_user!
      redirect_to('/login', alert: 'You need to login!') unless current_user
  end
  
end

NCIHealthStore/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :purchase_order_required, except: [:index]
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  def index
    @order_items = OrderItem.all
  end

  def show
  end

  def new
    @order_item = purchase_order.order_items.new
  end

  def edit
  end

  def create
    @order_item = purchase_order.order_items.new(order_item_params)
    if @order_item.save
      purchase_order_update_total
      redirect_to purchase_order_path(params[:purchase_order_id]), notice: 'Order item was successfully created.'
    else
      flash[:warning] = @order_item.errors.full_messages.first
      redirect_to new_purchase_order_order_item_path(params[:purchase_order_id])
    end
  end


  def update
    if @order_item.update(order_item_params)
      purchase_order_update_total
      redirect_to purchase_order_path(params[:purchase_order_id]), notice: 'Order item was successfully updated.'
    else
      flash[:warning] = @order_item.errors.full_messages.first
      redirect_to edit_purchase_order_order_item_path(params[:purchase_order_id])
    end
  end

  def destroy
    @order_item.destroy
    purchase_order_update_total
    redirect_to purchase_order_path(params[:purchase_order_id]), notice: 'Order item was successfully destroyed.'
  end

  private
  
    def set_order_item
      @order_item = purchase_order.order_items.find(params[:id]) if purchase_order.present?
    end
    
    def purchase_order
      @purchase_order ||= PurchaseOrder.find_by(id: params[:purchase_order_id])
    end    
    

    def order_item_params
      params.require(:order_item).permit(:item_title, :item_description, :item_quantity, :item_price)
    end
    
    def purchase_order_required
      redirect_to(purchase_orders_path, alert: 'Purchase order not found.') unless purchase_order.present?
    end
    
    def purchase_order_update_total
      total = purchase_order.calculate_total
      purchase_order.update_attribute(:total, total)
      purchase_order.save
    end
    
end

NCIHealthStore/app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  def index
    @purchase_orders = PurchaseOrder.all
  end

  def show
  end

  def new
    @purchase_order = PurchaseOrder.new
  end

  def edit
  end

  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)
    if @purchase_order.save 
      purchase_order_update_total
      redirect_to @purchase_order, notice: 'Purchase order was successfully created.' 
    else
      flash[:warning] = @purchase_order.errors.full_messages.first
      redirect_to new_purchase_order_path
    end
  end

  def update
    if @purchase_order.update(purchase_order_params)
      purchase_order_update_total
      redirect_to @purchase_order, notice: 'Purchase order was successfully updated.'
    else
      flash[:warning] = @purchase_order.errors.full_messages.first
      redirect_to edit_purchase_order_path
    end
  end

  def destroy
    @purchase_order.destroy
    redirect_to purchase_orders_url, notice: 'Purchase order was successfully destroyed.'
  end

  private
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    def purchase_order_params
      params.require(:purchase_order).permit(:client_number, :delivery_address, :delivery_city, :delivery_country, :delivery_fee, :total)
    end
    
    def purchase_order_update_total
      total = @purchase_order.calculate_total
      @purchase_order.update_attribute(:total, total)
      @purchase_order.save
    end
    
end

NCIHealthStore/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticate_user!
    
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:notice] = "Welcome back!"
            redirect_to purchase_orders_path
        else 
            flash[:warning] = "Incorrect email or password. Please try again."
            redirect_to '/login'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "See you later!"
        redirect_to '/login'
    end
    
end

NCIHealthStore/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def about
  end
end

NCIHealthStore/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user!
    
    def new
    end

    def create 
        user = User.new(
            name: params[:name],
            email: params[:email],
            password: params[:password],
            password_confirmation: params[:password_confirmation])

        if user.save
            session[:user_id] = user.id
            redirect_to purchase_orders_path, notice: "Welcome to NCI Health Store!"
        else
            flash[:warning] = user.errors.full_messages.first
            redirect_to '/signup'
        end
    end
    
end

NCIHealthStore/app/helpers/application_helper.rb
module ApplicationHelper
end

NCIHealthStore/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

NCIHealthStore/app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

NCIHealthStore/app/helpers/sessions_helper.rb
module SessionsHelper
end

NCIHealthStore/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

NCIHealthStore/app/helpers/users_helper.rb
module UsersHelper
end

NCIHealthStore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NCI Health Store | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a  class="navbar-brand">NCI Health Store</a>
      
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          
          <% if @current_user %>
          
            <li class="nav-item mx-3">
              <a><%= link_to "Purchase orders", purchase_orders_path %></a>
            </li>
            
            <li class="nav-item mx-3">
              <a><%= link_to "Order items", order_items_path %></a>
            </li>
            
            <li class="nav-item mx-3">
              <a><%= link_to 'Logout', logout_path %></a></a>
            </li>
          
          <% else %>
          
            <li class="nav-item mx-3">
              <a><%= link_to "About", about_path %></a>
            </li>
          
            <li class="nav-item mx-3">
              <a><%= link_to 'Login', login_path %></a>
            </li>
            
            <li class="nav-item mx-3">
              <a><%= link_to 'Sign up', signup_path %></a>
            </li>
          
          <% end %>
          
          </ul>
          
          <% if @current_user %>
          
            <span class="navbar-text">
              Logged in as <%= @current_user.name %>
            </span>
            
          <% end %>
          
          
      </div>
    </nav>
    <%= content_tag :div, flash[:notice], class: "alert alert-success" if flash[:notice].present? %>
    <%= content_tag :div, flash[:alert], class: "alert alert-danger" if flash[:alert].present? %>
    <%= content_tag :div, flash[:warning], class: "alert alert-warning" if flash[:warning].present? %>
    <div class="view">
      <div id="content" class="container min-vh-100 p-0">
        <div class="row collapse show no-gutters d-flex h-100 position-relative">
          <div class="col-12 pt-4">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    
  </body>
</html>

NCIHealthStore/app/views/order_items/_form_edit.html.erb
<%= form_for([@purchase_order, order_item]) do |f| %>

  <div class="form-group">
    <%= f.label :item_title %>
    <%= f.text_field :item_title, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_description %>
    <%= f.text_field :item_description, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_quantity %>
    <%= f.number_field :item_quantity, step: 'any', class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_price %>
    <%= f.number_field :item_price, step: 'any', class:'form-control'  %>
  </div>

  <div class="form-group text-center">
    <%= f.submit 'Save',  class: 'btn btn-primary' %>
    <%= link_to 'Cancel', purchase_order_order_item_path(@order_item.purchase_order.id, @order_item),  class: 'btn btn-link' %>
  </div>
<% end %>

NCIHealthStore/app/views/order_items/_form_new.html.erb
<%= form_for([@purchase_order, order_item]) do |f| %>

  <div class="form-group">
    <%= f.label :item_title %>
    <%= f.text_field :item_title, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_description %>
    <%= f.text_field :item_description, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_quantity %>
    <%= f.number_field :item_quantity, step: 'any', class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :item_price %>
    <%= f.number_field :item_price, step: 'any', class:'form-control'  %>
  </div>

  <div class="form-group text-center">
    <%= f.submit 'Save',  class: 'btn btn-primary' %>
    <%= link_to 'Cancel', purchase_order_path(@order_item.purchase_order.id),  class: 'btn btn-link' %>
  </div>
<% end %>

NCIHealthStore/app/views/order_items/edit.html.erb
<%= provide(:title, "Edit Order Item") %>

<h2 class="text-center m-3">Editing Order Item <%= @order_item.id.to_s %></h2>

<div class="card d-flex display:block mx-auto" style="width: 40rem;">
    <div class="card-body">
        <%= render 'form_edit', order_item: @order_item %>
    </div>
</div>

NCIHealthStore/app/views/order_items/index.html.erb
<%= provide(:title, "Order Items") %>

<div class='my-3'>
  <h2>Order Items</h2>
</div>

  <div class="card d-flex display:block mx-auto">
    <table class="table table-striped table-bordered mb-0">
      <thead>
        <tr>
          <th scope="col">Purchase Order</th>
          <!--<th scope="col">Purchase Order total</th>-->
          <th scope="col">Order item</th>
          <th scope="col">Item title</th>
          <th scope="col">Item description</th>
          <th scope="col">Item price</th>
          <th scope="col">Item quantity</th>
          <th scope="col">Item total price</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
    
      <tbody>
        <% @order_items.each do |order_item| %>
          <tr>
            <td><%= link_to ('Purchase Order ' + order_item.purchase_order.id.to_s), purchase_order_path(order_item.purchase_order_id) %></td>
            <!--<td><%#= order_item.purchase_order.total %></td>-->
            <td><%= link_to ('Order Item ' + order_item.id.to_s), purchase_order_order_item_path(order_item.purchase_order_id, order_item) %></td>
            <td><%= order_item.item_title %></td>
            <td><%= order_item.item_description %></td>
            <td><%= order_item.item_price %></td>
            <td><%= order_item.item_quantity %></td>
            <td><%= order_item.item_quantity * order_item.item_price %></td>
            <!--<td><#%= order_item.item_image_url %></td>-->
            <td><%= link_to 'Delete', [order_item.purchase_order, order_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <br>
</div>

NCIHealthStore/app/views/order_items/new.html.erb
<%= provide(:title, "New Order Item") %>

<h2 class="text-center m-3">New Order Item in Purchase Order <%= @purchase_order.id %></h2>

<div class="card d-flex display:block mx-auto" style="width: 40rem;">
    <div class="card-body">
        <%= render 'form_new', order_item: @order_item %>
    </div>
</div>

NCIHealthStore/app/views/order_items/show.html.erb
<%= provide(:title, "Order Item " + @order_item.id.to_s) %>

<div class="card d-flex display:block mx-auto" style="width: 40rem;">
  <div class="card-header">
    Order Item <%= @order_item.id %>
  </div>
  <div class="card-body">
    
    <p class="card-text">
      <strong>Item title:</strong>
      <%= @order_item.item_title %>
    </p>
    
    <p class="card-text">
      <strong>Item description:</strong>
      <%= @order_item.item_description %>
    </p>
    
    <p class="card-text">
      <strong>Item quantity:</strong>
      <%= @order_item.item_quantity %>
    </p class="card-text">
    
    <p class="card-text">
      <strong>Item price:</strong>
      <%= @order_item.item_price %>
    </p>
    
    <div class="text-center py-3">
      <%= link_to 'Edit', edit_purchase_order_order_item_path([@purchase_order, @order_item]), class:"btn btn-success mx-2" %>
      <%= link_to 'Delete', [@purchase_order, @order_item], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger mx-2" %>
      <%= link_to 'Back to Purchase Order', @purchase_order, class:"btn btn-link mx-2" %>
    </div>
  </div>
</div>

NCIHealthStore/app/views/purchase_orders/_form.html.erb
<%= form_for(purchase_order) do |f| %>

  <div class="form-group">
    <%= f.label :client_number %>
    <%= f.text_field :client_number, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :delivery_address %>
    <%= f.text_field :delivery_address, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :delivery_city %>
    <%= f.text_field :delivery_city, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :delivery_country %>
    <%= f.text_field :delivery_country, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :delivery_fee %>
    <%= f.number_field :delivery_fee, step: "any", class:'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit 'Save',  class: 'btn btn-primary' %>
    <%= link_to 'Cancel', purchase_orders_path,  class: 'btn btn-link' %>
  </div>
<% end %>

NCIHealthStore/app/views/purchase_orders/edit.html.erb
<%= provide(:title, "Edit Purchase Order") %>

<h2 class="text-center m-3">Editing Purchase Order <%= @purchase_order.id.to_s %></h2>

<div class="card d-flex display:block mx-auto" style="width: 40rem;">
    <div class="card-body">
        <%= render 'form', purchase_order: @purchase_order %>
    </div>
</div>

NCIHealthStore/app/views/purchase_orders/index.html.erb
<%= provide(:title, "Purchase Orders") %>

<div class='my-3'>
  <h2>Purchase Orders</h2>
</div>

<div class="card d-flex display:block mx-auto">
  <table class="table table-striped table-bordered mb-0">
    <thead>
      <tr>
        <th scope="col">Purchase Order Id</th>
        <th scope="col">Client number</th>
        <th scope="col">Delivery address</th>
        <th scope="col">Delivery city</th>
        <th scope="col">Delivery country</th>
        <th scope="col">Total</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
  
    <tbody>
      <% @purchase_orders.each do |purchase_order| %>
        <tr>
          <td><%= link_to ("Purchase Order " + purchase_order.id.to_s), purchase_order%></td>
          <td><%= purchase_order.client_number %></td>
          <td><%= purchase_order.delivery_address %></td>
          <td><%= purchase_order.delivery_city %></td>
          <td><%= purchase_order.delivery_country %></td>
          <td><%= purchase_order.total %></td>
          <td><%= link_to 'Delete', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Purchase Order', new_purchase_order_path, class:'btn btn-primary' %>

NCIHealthStore/app/views/purchase_orders/new.html.erb
<%= provide(:title, "New Purchase Order") %>

<h2 class="text-center m-3">New Purchase Order</h2>
    
<div class="card d-flex display:block mx-auto" style="width: 40rem;">
    <div class="card-body">
        <%= render 'form', purchase_order: @purchase_order %>
    </div>
</div>
            

NCIHealthStore/app/views/purchase_orders/show.html.erb
<%= provide(:title, "Purchase Order" + @purchase_order.id.to_s) %>

<div class="card">
  <div class="card-header">
    Purchase Order <%= @purchase_order.id %>
  </div>
  <div class="card-body">
    <p class="card-text">
      <strong>Client number: </strong>
      <%= @purchase_order.client_number %>
    </p>
    
    <p class="card-text">
      <strong>Delivery address:</strong>
      <%= @purchase_order.delivery_address %>
    </p>
    
    <p class="card-text">
      <strong>Delivery city:</strong>
      <%= @purchase_order.delivery_city %>
    </p>
    
    <p class="card-text">
      <strong>Delivery country:</strong>
      <%= @purchase_order.delivery_country %>
    </p>
    
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">Order Item Id</th>
          <th scope="col">Item title</th>
          <th scope="col">Item description</th>
          <th scope="col">Item price</th>
          <th scope="col">Item quantity</th>
          <th scope="col">Item total price</th>
          <!--<th scope="col">Item image url</th>-->
          <th scope="col">Delete</th>
        </tr>
      </thead>
    
      <tbody>
        <% @purchase_order.order_items.each do |order_item| %>
          <tr>
            <td><%= link_to ("Order Item " + order_item.id.to_s), purchase_order_order_item_path(@purchase_order, order_item) %></td>
            <td><%= order_item.item_title %></td>
            <td><%= order_item.item_description %></td>
            <td><%= order_item.item_price %></td>
            <td><%= order_item.item_quantity %></td>
            <td><%= order_item.item_quantity * order_item.item_price %></td>
            <td><%= link_to 'Delete', [@purchase_order, order_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <p class="d-flex justify-content-end mx-5 font-weight-bold">
      Delivery fee: <%= @purchase_order.delivery_fee %>
    </p>
    
    <p class="d-flex justify-content-end mx-5 font-weight-bold">
      Total: <%= @purchase_order.total %>
    </p>
    
    <div class="text-center py-3">
      <%= link_to 'Edit information', edit_purchase_order_path(@purchase_order), class:"btn btn-success mx-2"%>
      <%= link_to 'Add order item', new_purchase_order_order_item_path(@purchase_order), class:"btn btn-primary mx-2" %>
      <%= link_to 'Delete', @purchase_order, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger mx-2" %>
      <%= link_to 'Back to list', purchase_orders_path, class:"btn btn-link mx-2" %>
    </div>
  </div>
</div>

NCIHealthStore/app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>

<div class="my-3">
    <h2>About us</h2>

    <h5 class="my-3">Welcome to NCI Health Store!</h5>

    <p>
        The NCI Health Store employees can access the Purchase Orders of the NCI Health Store once signed up or logged in.
    </p>

    <p>
        This application was created and designed by Alexia FALCOZ (x19144733).
    </p>


</div>

NCIHealthStore/app/views/users/new.html.erb
<%= provide(:title, "Sign Up") %>
<div class="my-3">
 <h2 class="text-center"> Create your account</h2>
 
 <div class="card d-flex display:block mx-auto" style="width: 30rem;">
  <div class="card-body">
   
   
   <%=form_tag "/users", method: :post do%>
   
    <div class="form-group">
     <%= label_tag :name%>
     <%= text_field_tag :name, nil, placeholder: 'Full name', autocomplete: 'off', class: 'form-control'%>
    </div>
    <div class="form-group">
     <%= label_tag :email%>
     <%= text_field_tag :email, nil, placeholder: 'Email address', autocomplete: 'off', class: 'form-control'%>
    </div>
    <div class="form-group">
     <%= label_tag :password%>
     <%= password_field_tag :password, nil, placeholder: 'Password', autocomplete: 'off', class: 'form-control'%>
    </div>
    <div class="form-group">
     <%= label_tag :password_confirmation%>
     <%= password_field_tag :password_confirmation, nil, placeholder: 'Confirm password', autocomplete: 'off', class: 'form-control'%>
    </div>
   
    <div class="text-center">
     <%= submit_tag "Sign Up", class: "btn btn-primary"%>
    </div>
   <%end%>
  </div>
 </div>
</div>